language: java
jdk: oraclejdk11

script:
  - mvn -e verify

notifications:
  email:
    recipients:
      - ilya.tfb@yandex.ru
    on_failure: always
    on_success: change

after_success:
  - bash <(curl -s https://codecov.io/bash)